input_feat_dim: 9
gnn_hidden_dim: 1024
num_layers: 5
num_heads: 8
method: laplacian
d_p: 64
d_e: 64
use_graph_token: True
max_position_embeddings: 102
graph_encoder_ckpt: /data/all_checkpoints/Custom_gnn_models/TokenGT/best-model-5M.ckpt
gnn_type: tokengt